# Generated by Django 4.2.3 on 2023-07-25 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_category_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_products', to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_listed_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
