# Generated by Django 4.2.3 on 2023-07-25 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_commentonlisting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentonlisting',
            old_name='commment',
            new_name='comment',
        ),
    ]
